name: model-training
on:
  # Trigger the workflow on push or pull request,
  # for the main and dev branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  issues:
    types: [opened, edited, milestoned]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python mushrooms-tree.py

          cat outputs/metrics.txt >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
